services:
  calc_server:
    build: ./calcApp
    container_name: calc_server

    command: python3 calcServer.py "192.168.3.6" "9998"

    networks:
      test_net:
        ipv4_address: "192.168.3.6"

  jenkins-server:
    build: ./jenkins_server
    container_name: jenkins-server

    networks:
      test_net:
        ipv4_address: "192.168.3.7"
    volumes:
      - jenkins_home:/var/jenkins_home
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
    driver: local

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.3.0/24"
