services:
  calc_server:
    build: ./calcApp
    container_name: calc_server

    command: sh /app/setup.sh 

    networks:
      test_net:
        ipv4_address: "192.168.3.6"

  bamboo-server:
    image: atlassian/bamboo
    container_name: bamboo-server

    depends_on:
      - db

    networks:
      test_net:
        ipv4_address: "192.168.3.7"
    volumes:
      - bambooVolume:/var/atlassian/application-data/bamboo

  bamboo-agent:
    build: ./bamboo_server/bamboo_agent_img
    container_name: bamboo-agent

    depends_on:
      - bamboo-server

    environment:
      - BAMBOO_SERVER=http://192.168.3.7:8085

    networks:
      test_net:
        ipv4_address: "192.168.3.10"

  db:
    image: postgres:16
    container_name: db
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      test_net:
        ipv4_address: "192.168.3.8"

volumes:
  bambooVolume:
    driver: local
  pgdata:
    driver: local

networks:
  test_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.3.0/24"
